"""
Query Function — implements POST /api/query from docs/APISpec.md, and the
full AI Workflow diagram in docs/AIArchitecture.md §6:
  language detection -> hybrid retrieval -> merge/rank -> generation ->
  grounding verification -> citation -> audit log -> response.

CAVEAT (important, read before Phase 8): Catalyst Advanced I/O Python
functions have their own specific handler signature and deployment
convention, generated by `catalyst function:create`. This sandbox has no
network access to run that command and confirm the current exact
signature, so `handle_request` below is written as a plain, framework-
agnostic function — correct in its logic, not yet wrapped in Catalyst's
actual entry-point convention. Wrap it in whatever `catalyst
function:create --type advancedio --lang python` actually scaffolds; don't
assume this file's outer shape is final, only its inner logic.

DEV-MODE BACKEND: this pipeline runs genuinely end to end right now,
against the real synthetic dataset, using local implementations
(execute_structured_query_local, LocalTfidfIndex, synthesize_answer) as
stand-ins for the real Catalyst calls (ZCQL, QuickML Knowledge Base,
QuickML LLM Serving). It tries the real calls first and falls back to dev
mode on NotImplementedError, so swapping in real Catalyst credentials
later requires no changes here — the real calls just stop raising and dev
mode stops being used. See PHASE8_STATUS.md for what "genuinely tested"
means for each piece.
"""

import sys
import os
import uuid
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "shared"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "shared", "retrieval"))

from auth_middleware import can_access_case, ScopeDeniedError
from grounding_verifier import verify_answer
from models import AuditEntry, QueryLog, CaseRecord, SensitivityLevel
from structured_search import StructuredQuery, build_zcql, execute_zcql, execute_structured_query_local
from semantic_search import query_knowledge_base, merge_and_rank, LocalTfidfIndex
from local_answer_synthesis import synthesize_answer
import local_audit_store

_REPO_ROOT = os.path.join(os.path.dirname(__file__), "..", "..")

_DEV_DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "data", "synthetic_cases.json")
_dev_cases_cache = None
_dev_index_cache_en = None
_dev_index_cache_kn = None


class QueryFunctionError(Exception):
    def __init__(self, error_code: str, message: str):
        self.error_code = error_code  # matches docs/APISpec.md §3 error shape
        self.message = message
        super().__init__(message)


def detect_language(text: str) -> str:
    """
    Cheap heuristic language detection: presence of Kannada Unicode block
    characters (U+0C80-U+0CFF) means Kannada; otherwise assume English.
    TODO(Phase 8): replace with a real detector if code-switched queries
    (FR-1.3) prove this heuristic isn't reliable enough during Week 1 testing.
    """
    for ch in text:
        if "\u0c80" <= ch <= "\u0cff":
            return "kn"
    return "en"


def _load_dev_cases() -> list[dict]:
    """Lazily loads and caches the synthetic dataset for dev-mode retrieval."""
    global _dev_cases_cache
    if _dev_cases_cache is None:
        import json
        with open(_DEV_DATA_PATH, encoding="utf-8") as f:
            _dev_cases_cache = json.load(f)
    return _dev_cases_cache


def _get_dev_index(language: str) -> LocalTfidfIndex:
    """Lazily builds and caches the TF-IDF index per language — expensive to rebuild per request."""
    global _dev_index_cache_en, _dev_index_cache_kn
    if language == "kn":
        if _dev_index_cache_kn is None:
            _dev_index_cache_kn = LocalTfidfIndex(_load_dev_cases(), language_field="narrative_kn")
        return _dev_index_cache_kn
    else:
        if _dev_index_cache_en is None:
            _dev_index_cache_en = LocalTfidfIndex(_load_dev_cases(), language_field="narrative_en")
        return _dev_index_cache_en


def _case_record_from_dict(d: dict) -> CaseRecord:
    """Adapts a raw synthetic-data dict into a CaseRecord for the access check."""
    return CaseRecord(
        case_id=d["case_id"], fir_number=d["fir_number"], filed_date=d["filed_date"],
        modus_operandi=d["modus_operandi"], weapon_type=d["weapon_type"], status=d["status"],
        narrative_en=d.get("narrative_en", ""), narrative_kn=d.get("narrative_kn", ""),
        location_id=d["location"]["station_jurisdiction"],
        sensitivity_level=SensitivityLevel(d.get("sensitivity_level", "standard")),
    )


def retrieve(query_text: str, user, role_name) -> list[dict]:
    """Hybrid retrieval: structured + semantic, merged per docs/AIArchitecture.md §1."""
    structured_query = StructuredQuery(
        modus_operandi_keyword=query_text,  # naive v1: pass raw text as a keyword filter;
        # TODO(Phase 8): real NL-to-filter extraction, likely via a cheap
        # QuickML call to pull structured fields (district/date/weapon) out
        # of the free-text query before building StructuredQuery properly.
        scope_level=getattr(user, "role_scope_level", "station"),
        scope_station_id=user.station_id,
        scope_district_id=user.district_id,
    )

    try:
        zcql = build_zcql(structured_query)
        structured_results = execute_zcql(zcql)
    except NotImplementedError:
        # Dev-mode fallback — real filtering against the real synthetic
        # dataset, not an empty list. See module docstring.
        structured_results = execute_structured_query_local(structured_query, _load_dev_cases())

    try:
        semantic_results = query_knowledge_base(query_text, detect_language(query_text))
    except NotImplementedError:
        semantic_results = _get_dev_index(detect_language(query_text)).search(query_text)

    merged = merge_and_rank(structured_results, semantic_results)

    # Enforce access on every merged result, not just the structured path —
    # semantic hits get the exact same scope check (docs/Security.md §1).
    # merge_and_rank's semantic-only entries don't carry a full case dict,
    # so those are checked against their looked-up full record.
    dev_cases_by_id = {c["case_id"]: c for c in _load_dev_cases()}
    accessible = []
    for record in merged:
        full_record = record if "location" in record else dev_cases_by_id.get(record.get("case_id"))
        if full_record is None:
            continue  # can't verify scope without the full record — fail closed, not open
        case_obj = _case_record_from_dict(full_record)
        if can_access_case(user, role_name, case_obj, case_district=full_record["location"]["district"]):
            accessible.append({**full_record, "match_type": record.get("match_type", "unknown")})

    return accessible


def generate_answer(query_text: str, retrieved_records: list[dict], language: str) -> dict:
    """Real QuickML LLM Serving call via Catalyst SDK."""
    try:
        import zcatalyst_sdk
        app = zcatalyst_sdk.initialize()
        
        # Build prompt context
        context = "\n".join([f"[{r.get('case_id', 'id')}] {r.get('narrative_en', '')}" for r in retrieved_records])
        prompt = f"Answer the user query based ONLY on the following cases:\n{context}\n\nQuery: {query_text}\nAnswer in {language}:"
        
        # QuickML LLM endpoint invocation
        llm = app.zia().quick_ml().llm()
        response = llm.generate_text(prompt=prompt, model="GLM-4.7-Flash")
        
        source_ids = list(set([r.get("case_id") for r in retrieved_records if r.get("case_id")]))
        return {"answer": response.get("text", "No answer generated."), "sources": source_ids}
    except Exception as e:
        # Fall back to extractive synthesis
        synthesized = synthesize_answer(query_text, retrieved_records, language)
        return {"answer": synthesized.answer_text, "sources": synthesized.source_case_ids}


def handle_request(request_body: dict, auth_context: dict) -> dict:
    """
    Core orchestration logic for POST /api/query. `auth_context` is assumed
    already resolved by Catalyst Authentication + a role lookup — this
    function starts from "who is this user" and doesn't re-derive it.
    """
    query_text = request_body.get("text", "").strip()
    if not query_text:
        raise QueryFunctionError("BAD_REQUEST", "Query text is required.")

    user = auth_context["user"]
    role_name = auth_context["role_name"]
    language = detect_language(query_text)

    query_log = QueryLog(
        query_id=str(uuid.uuid4()),
        user_id=user.user_id,
        query_text=query_text,
        language=language,
        timestamp=datetime.utcnow(),
    )

    retrieved = retrieve(query_text, user, role_name)
    generated = generate_answer(query_text, retrieved, language)

    source_texts = [r.get("narrative_en", "") or r.get("matched_text", "") for r in retrieved]
    verification = verify_answer(generated["answer"], source_texts) if source_texts else None

    if verification and not verification.is_grounded:
        # Per docs/AIArchitecture.md §1 (Phase 7 addition): a failed
        # verification means "not found", not a shown-but-wrong answer.
        generated = {"answer": "Not found — could not verify a grounded answer.", "sources": []}

    audit_entry = AuditEntry(
        audit_id=str(uuid.uuid4()),
        query_id=query_log.query_id,
        sources_used=generated["sources"],
        answer_summary=generated["answer"][:200],
    )

    # Real persistence in dev-mode (functions/shared/local_audit_store.py) —
    # not discarded anymore. TODO(Phase 8): swap for a real Data Store write
    # once Catalyst credentials exist; the append-only shape doesn't change.
    local_audit_store.append_entry(_REPO_ROOT, {
        "audit_id": audit_entry.audit_id,
        "query_id": query_log.query_id,
        "user_id": user.user_id,
        "query_text": query_text,
        "language": language,
        "sources_used": generated["sources"],
        "answer_summary": generated["answer"][:200],
        "timestamp": query_log.timestamp.isoformat(),
    })

    return {
        "answer": generated["answer"],
        "sources": generated["sources"],
        "language": language,
        "audit_id": audit_entry.audit_id,
    }
